import type { Metadata } from "next";
import { IBM_Plex_Sans_Thai } from "next/font/google";
import "./globals.css";
// import Providers from "./providers";
import { Navbar } from "./components/Navbar";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";

const IBMPlex = IBM_Plex_Sans_Thai({
  subsets: ["thai"],
  // variable: "--font-ibm-plex-sans-thai",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <body className={`${IBMPlex.className} antialiased`}>
        <NextIntlClientProvider>
          <Navbar />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
